user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
  worker_connections  1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;

  map $uri $vod_cache_control {
    ~*\.(m3u8|mpd)$   "public, max-age=5";
    ~*\.(m4s|mp4|ts)$ "public, max-age=86400";
    default           "public, max-age=60";
  }

  include /etc/nginx/conf.d/*.conf;
}
